FROM confluentinc/cp-kafka-connect:7.4.1

USER root:root

RUN microdnf update
RUN microdnf install -y vi
RUN microdnf install -y wget
RUN microdnf install procps
RUN microdnf install -y lsof
RUN microdnf install -y \
   java-1.8.0-openjdk \
   java-1.8.0-openjdk-devel

# Install Kanister Tools
RUN wget https://raw.githubusercontent.com/kanisterio/kanister/master/scripts/get.sh
RUN ln -s /usr/bin/sha256sum /usr/bin/shasum
RUN sed -i 's/shasum -a 256/shasum/g' get.sh
RUN sh get.sh

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk/
RUN microdnf install git -y
RUN java -version
RUN git clone https://github.com/adobe/kafka-connect-s3.git
RUN cd kafka-connect-s3 && ./gradlew shadowJar

# copy the jar files
RUN cp ./kafka-connect-s3/build/libs/kafka-connect-s3-chart/kafka-connect/0.0.4-2a8a4aa-all.jar /opt/

# adding script to monitor sink
COPY monitorsink.sh monitorsink.sh

# adding script to monitor source
COPY monitorsource.sh monitorsource.sh

# Install kafka mc client
RUN curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o /opt/mc
RUN chmod +x /opt/mc
